### ISSUE TITLE
有計劃支持.jxl 的圖像嗎？

### ISSUE THREAD

**Issue by n-buna404** [hbl917070/TiefSee#9]
[https://github.com/libjxl/libjxl](url)
JPEG XL 是新型圖像，支持loseless 和 lossy compression. 
Benchmark[https://docs.google.com/spreadsheets/d/1ju4q1WkaXT7WoxZINmQpf4ElgMD2VMlqeDN2DuZ6yJ8/edit#gid=1919028011](url)

**Comment by hbl917070** [comment]
Tiefsee4用的是新版本的Magick.NET，是能夠打開jxl圖片的
但開啟的速度慢到會懷疑人生
如果有更好的C#函式庫，我再測試看看能不能導入
[https://github.com/hbl917070/Tiefsee4](https://github.com/hbl917070/Tiefsee4)

Tiefsee4是基於webview2，也就是edge瀏覽器
也就是說edge如果預設支援jxl圖片的話，就可以不用依賴第三方函式庫了

**Comment by n-buna404** [comment]
好的等Tiefsee4 stable release。我再來試試
